# SPDX-License-Identifier: GPL-2.0
all:

TEST_PROGS := dax-kmem-hotplug.sh

TEST_GEN_FILES += cram_readable_tool
TEST_GEN_FILES += cram_fork_tool
TEST_GEN_FILES += cram_ops_tool
include ../lib.mk

TEST_PROGS += cram_readable.sh
TEST_PROGS += cram_fork.sh
TEST_PROGS += cram_ops.sh
